import SwiftUI
import SaneUI

typealias SaneBarChrome = SaneUI.SanePanelChrome
typealias ChromeGlassRoundedBackground = SaneUI.SaneGlassRoundedBackground
typealias ChromeGlassCapsuleBackground = SaneUI.SaneGlassCapsuleBackground
typealias ChromeGlassCircleBackground = SaneUI.SaneGlassCircleBackground
typealias ChromePressablePlainStyle = SaneUI.SanePressablePlainStyle
typealias ChromeActionButtonStyle = SaneUI.SaneActionButtonStyle
typealias ChromeSegmentedChoiceButton = SaneUI.SaneSegmentedChoiceButton
typealias ChromeBadge = SaneUI.SaneAccentBadge
