///
/// @Generated by Mockolo
///

import AppKit
import Combine
import CoreWLAN
import Foundation
import IOKit
import KeyboardShortcuts
import os
@testable import SaneBar
import SwiftUI

final class PersistenceServiceProtocolMock: PersistenceServiceProtocol, @unchecked Sendable {
    init() {}

    private let saveSettingsState = MockoloMutex(MockoloHandlerState<SaneBarSettings, @Sendable (SaneBarSettings) throws -> Void>())
    var saveSettingsCallCount: Int {
        saveSettingsState.withLock(\.callCount)
    }

    var saveSettingsArgValues: [SaneBarSettings] {
        saveSettingsState.withLock(\.argValues).map(\.value)
    }

    var saveSettingsHandler: (@Sendable (SaneBarSettings) throws -> Void)? {
        get { saveSettingsState.withLock(\.handler) }
        set { saveSettingsState.withLock { $0.handler = newValue } }
    }

    func saveSettings(_ settings: SaneBarSettings) throws {
        warnIfNotSendable(settings)
        let saveSettingsHandler = saveSettingsState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init(settings))
            return state.handler
        }
        if let saveSettingsHandler {
            try saveSettingsHandler(settings)
        }
    }

    private let loadSettingsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () throws -> SaneBarSettings>())
    var loadSettingsCallCount: Int {
        loadSettingsState.withLock(\.callCount)
    }

    var loadSettingsHandler: (@Sendable () throws -> SaneBarSettings)? {
        get { loadSettingsState.withLock(\.handler) }
        set { loadSettingsState.withLock { $0.handler = newValue } }
    }

    func loadSettings() throws -> SaneBarSettings {
        let loadSettingsHandler = loadSettingsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let loadSettingsHandler {
            return try loadSettingsHandler()
        }
        fatalError("loadSettingsHandler returns can't have a default value thus its handler must be set")
    }

    private let clearAllState = MockoloMutex(MockoloHandlerState<Never, @Sendable () throws -> Void>())
    var clearAllCallCount: Int {
        clearAllState.withLock(\.callCount)
    }

    var clearAllHandler: (@Sendable () throws -> Void)? {
        get { clearAllState.withLock(\.handler) }
        set { clearAllState.withLock { $0.handler = newValue } }
    }

    func clearAll() throws {
        let clearAllHandler = clearAllState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let clearAllHandler {
            try clearAllHandler()
        }
    }
}

final class SearchServiceProtocolMock: SearchServiceProtocol, @unchecked Sendable {
    init() {}

    private let getRunningAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var getRunningAppsCallCount: Int {
        getRunningAppsState.withLock(\.callCount)
    }

    var getRunningAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { getRunningAppsState.withLock(\.handler) }
        set { getRunningAppsState.withLock { $0.handler = newValue } }
    }

    func getRunningApps() async -> [RunningApp] {
        let getRunningAppsHandler = getRunningAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let getRunningAppsHandler {
            return await getRunningAppsHandler()
        }
        return [RunningApp]()
    }

    private let getMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var getMenuBarAppsCallCount: Int {
        getMenuBarAppsState.withLock(\.callCount)
    }

    var getMenuBarAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { getMenuBarAppsState.withLock(\.handler) }
        set { getMenuBarAppsState.withLock { $0.handler = newValue } }
    }

    func getMenuBarApps() async -> [RunningApp] {
        let getMenuBarAppsHandler = getMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let getMenuBarAppsHandler {
            return await getMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let getHiddenMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var getHiddenMenuBarAppsCallCount: Int {
        getHiddenMenuBarAppsState.withLock(\.callCount)
    }

    var getHiddenMenuBarAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { getHiddenMenuBarAppsState.withLock(\.handler) }
        set { getHiddenMenuBarAppsState.withLock { $0.handler = newValue } }
    }

    func getHiddenMenuBarApps() async -> [RunningApp] {
        let getHiddenMenuBarAppsHandler = getHiddenMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let getHiddenMenuBarAppsHandler {
            return await getHiddenMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let getAlwaysHiddenMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var getAlwaysHiddenMenuBarAppsCallCount: Int {
        getAlwaysHiddenMenuBarAppsState.withLock(\.callCount)
    }

    var getAlwaysHiddenMenuBarAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { getAlwaysHiddenMenuBarAppsState.withLock(\.handler) }
        set { getAlwaysHiddenMenuBarAppsState.withLock { $0.handler = newValue } }
    }

    func getAlwaysHiddenMenuBarApps() async -> [RunningApp] {
        let getAlwaysHiddenMenuBarAppsHandler = getAlwaysHiddenMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let getAlwaysHiddenMenuBarAppsHandler {
            return await getAlwaysHiddenMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let cachedMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> [RunningApp]>())
    var cachedMenuBarAppsCallCount: Int {
        cachedMenuBarAppsState.withLock(\.callCount)
    }

    var cachedMenuBarAppsHandler: (@Sendable () -> [RunningApp])? {
        get { cachedMenuBarAppsState.withLock(\.handler) }
        set { cachedMenuBarAppsState.withLock { $0.handler = newValue } }
    }

    @MainActor
    func cachedMenuBarApps() -> [RunningApp] {
        let cachedMenuBarAppsHandler = cachedMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let cachedMenuBarAppsHandler {
            return cachedMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let cachedHiddenMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> [RunningApp]>())
    var cachedHiddenMenuBarAppsCallCount: Int {
        cachedHiddenMenuBarAppsState.withLock(\.callCount)
    }

    var cachedHiddenMenuBarAppsHandler: (@Sendable () -> [RunningApp])? {
        get { cachedHiddenMenuBarAppsState.withLock(\.handler) }
        set { cachedHiddenMenuBarAppsState.withLock { $0.handler = newValue } }
    }

    @MainActor
    func cachedHiddenMenuBarApps() -> [RunningApp] {
        let cachedHiddenMenuBarAppsHandler = cachedHiddenMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let cachedHiddenMenuBarAppsHandler {
            return cachedHiddenMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let cachedAlwaysHiddenMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> [RunningApp]>())
    var cachedAlwaysHiddenMenuBarAppsCallCount: Int {
        cachedAlwaysHiddenMenuBarAppsState.withLock(\.callCount)
    }

    var cachedAlwaysHiddenMenuBarAppsHandler: (@Sendable () -> [RunningApp])? {
        get { cachedAlwaysHiddenMenuBarAppsState.withLock(\.handler) }
        set { cachedAlwaysHiddenMenuBarAppsState.withLock { $0.handler = newValue } }
    }

    @MainActor
    func cachedAlwaysHiddenMenuBarApps() -> [RunningApp] {
        let cachedAlwaysHiddenMenuBarAppsHandler = cachedAlwaysHiddenMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let cachedAlwaysHiddenMenuBarAppsHandler {
            return cachedAlwaysHiddenMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let cachedVisibleMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () -> [RunningApp]>())
    var cachedVisibleMenuBarAppsCallCount: Int {
        cachedVisibleMenuBarAppsState.withLock(\.callCount)
    }

    var cachedVisibleMenuBarAppsHandler: (@Sendable () -> [RunningApp])? {
        get { cachedVisibleMenuBarAppsState.withLock(\.handler) }
        set { cachedVisibleMenuBarAppsState.withLock { $0.handler = newValue } }
    }

    @MainActor
    func cachedVisibleMenuBarApps() -> [RunningApp] {
        let cachedVisibleMenuBarAppsHandler = cachedVisibleMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let cachedVisibleMenuBarAppsHandler {
            return cachedVisibleMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let refreshMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var refreshMenuBarAppsCallCount: Int {
        refreshMenuBarAppsState.withLock(\.callCount)
    }

    var refreshMenuBarAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { refreshMenuBarAppsState.withLock(\.handler) }
        set { refreshMenuBarAppsState.withLock { $0.handler = newValue } }
    }

    func refreshMenuBarApps() async -> [RunningApp] {
        let refreshMenuBarAppsHandler = refreshMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let refreshMenuBarAppsHandler {
            return await refreshMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let refreshHiddenMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var refreshHiddenMenuBarAppsCallCount: Int {
        refreshHiddenMenuBarAppsState.withLock(\.callCount)
    }

    var refreshHiddenMenuBarAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { refreshHiddenMenuBarAppsState.withLock(\.handler) }
        set { refreshHiddenMenuBarAppsState.withLock { $0.handler = newValue } }
    }

    func refreshHiddenMenuBarApps() async -> [RunningApp] {
        let refreshHiddenMenuBarAppsHandler = refreshHiddenMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let refreshHiddenMenuBarAppsHandler {
            return await refreshHiddenMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let refreshAlwaysHiddenMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var refreshAlwaysHiddenMenuBarAppsCallCount: Int {
        refreshAlwaysHiddenMenuBarAppsState.withLock(\.callCount)
    }

    var refreshAlwaysHiddenMenuBarAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { refreshAlwaysHiddenMenuBarAppsState.withLock(\.handler) }
        set { refreshAlwaysHiddenMenuBarAppsState.withLock { $0.handler = newValue } }
    }

    func refreshAlwaysHiddenMenuBarApps() async -> [RunningApp] {
        let refreshAlwaysHiddenMenuBarAppsHandler = refreshAlwaysHiddenMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let refreshAlwaysHiddenMenuBarAppsHandler {
            return await refreshAlwaysHiddenMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let refreshVisibleMenuBarAppsState = MockoloMutex(MockoloHandlerState<Never, @Sendable () async -> [RunningApp]>())
    var refreshVisibleMenuBarAppsCallCount: Int {
        refreshVisibleMenuBarAppsState.withLock(\.callCount)
    }

    var refreshVisibleMenuBarAppsHandler: (@Sendable () async -> [RunningApp])? {
        get { refreshVisibleMenuBarAppsState.withLock(\.handler) }
        set { refreshVisibleMenuBarAppsState.withLock { $0.handler = newValue } }
    }

    func refreshVisibleMenuBarApps() async -> [RunningApp] {
        let refreshVisibleMenuBarAppsHandler = refreshVisibleMenuBarAppsState.withLock { state in
            state.callCount += 1
            return state.handler
        }
        if let refreshVisibleMenuBarAppsHandler {
            return await refreshVisibleMenuBarAppsHandler()
        }
        return [RunningApp]()
    }

    private let activateState = MockoloMutex(MockoloHandlerState<(RunningApp, Bool), @Sendable (RunningApp, Bool) async -> Void>())
    var activateCallCount: Int {
        activateState.withLock(\.callCount)
    }

    var activateArgValues: [(RunningApp, Bool)] {
        activateState.withLock(\.argValues).map(\.value)
    }

    var activateHandler: (@Sendable (RunningApp, Bool) async -> Void)? {
        get { activateState.withLock(\.handler) }
        set { activateState.withLock { $0.handler = newValue } }
    }

    func activate(app: RunningApp, isRightClick: Bool) async {
        warnIfNotSendable(app, isRightClick)
        let activateHandler = activateState.withLock { state in
            state.callCount += 1
            state.argValues.append(.init((app, isRightClick)))
            return state.handler
        }
        if let activateHandler {
            await activateHandler(app, isRightClick)
        }
    }
}

final class NetworkTriggerServiceProtocolMock: NetworkTriggerServiceProtocol {
    init() {}
    init(currentSSID: String? = nil) {
        self.currentSSID = currentSSID
    }

    var currentSSID: String?

    private(set) var configureCallCount = 0
    var configureArgValues = [MenuBarManager]()
    var configureHandler: ((MenuBarManager) -> Void)?
    func configure(menuBarManager: MenuBarManager) {
        configureCallCount += 1
        configureArgValues.append(menuBarManager)
        if let configureHandler {
            configureHandler(menuBarManager)
        }
    }

    private(set) var startMonitoringCallCount = 0
    var startMonitoringHandler: (() -> Void)?
    func startMonitoring() {
        startMonitoringCallCount += 1
        if let startMonitoringHandler {
            startMonitoringHandler()
        }
    }

    private(set) var stopMonitoringCallCount = 0
    var stopMonitoringHandler: (() -> Void)?
    func stopMonitoring() {
        stopMonitoringCallCount += 1
        if let stopMonitoringHandler {
            stopMonitoringHandler()
        }
    }
}

final class HoverServiceProtocolMock: HoverServiceProtocol {
    init() {}
    init(isEnabled: Bool = false, scrollEnabled: Bool = false, clickEnabled: Bool = false, trackMouseLeave: Bool = false) {
        self.isEnabled = isEnabled
        self.scrollEnabled = scrollEnabled
        self.clickEnabled = clickEnabled
        self.trackMouseLeave = trackMouseLeave
    }

    private(set) var isEnabledSetCallCount = 0
    var isEnabled: Bool = false { didSet { isEnabledSetCallCount += 1 } }

    private(set) var scrollEnabledSetCallCount = 0
    var scrollEnabled: Bool = false { didSet { scrollEnabledSetCallCount += 1 } }

    private(set) var clickEnabledSetCallCount = 0
    var clickEnabled: Bool = false { didSet { clickEnabledSetCallCount += 1 } }

    private(set) var trackMouseLeaveSetCallCount = 0
    var trackMouseLeave: Bool = false { didSet { trackMouseLeaveSetCallCount += 1 } }

    private(set) var startCallCount = 0
    var startHandler: (() -> Void)?
    func start() {
        startCallCount += 1
        if let startHandler {
            startHandler()
        }
    }

    private(set) var stopCallCount = 0
    var stopHandler: (() -> Void)?
    func stop() {
        stopCallCount += 1
        if let stopHandler {
            stopHandler()
        }
    }
}

@MainActor
final class StatusBarControllerProtocolMock: StatusBarControllerProtocol, @unchecked Sendable {
    nonisolated init() {}
    init(mainItem: NSStatusItem, separatorItem: NSStatusItem) {
        self.mainItem = mainItem
        self.separatorItem = separatorItem
    }

    // Non-optional status items (matching protocol)
    var mainItem: NSStatusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
    var separatorItem: NSStatusItem = NSStatusBar.system.statusItem(withLength: 20)
    var alwaysHiddenSeparatorItem: NSStatusItem?

    private(set) var iconNameCallCount = 0
    var iconNameArgValues = [HidingState]()
    var iconNameHandler: ((HidingState) -> String)?
    func iconName(for state: HidingState) -> String {
        iconNameCallCount += 1
        iconNameArgValues.append(state)
        if let iconNameHandler {
            return iconNameHandler(state)
        }
        return ""
    }

    private(set) var createMenuCallCount = 0
    var createMenuArgValues = [MenuConfiguration]()
    var createMenuHandler: ((MenuConfiguration) -> NSMenu)?
    func createMenu(configuration: MenuConfiguration) -> NSMenu {
        createMenuCallCount += 1
        createMenuArgValues.append(configuration)
        if let createMenuHandler {
            return createMenuHandler(configuration)
        }
        fatalError("createMenuHandler returns can't have a default value thus its handler must be set")
    }
}

final class SettingsControllerProtocolMock: SettingsControllerProtocol {
    init() {}
    init(settings: SaneBarSettings) {
        _settings = settings
    }

    private(set) var settingsSetCallCount = 0
    private var _settings: SaneBarSettings! { didSet { settingsSetCallCount += 1 } }
    var settings: SaneBarSettings {
        get { _settings }
        set { _settings = newValue }
    }

    var settingsPublisher: AnyPublisher<SaneBarSettings, Never> { settingsPublisherSubject.eraseToAnyPublisher() }
    private(set) var settingsPublisherSubject = PassthroughSubject<SaneBarSettings, Never>()

    private(set) var loadCallCount = 0
    var loadHandler: (() throws -> Void)?
    func load() throws {
        loadCallCount += 1
        if let loadHandler {
            try loadHandler()
        }
    }

    private(set) var saveCallCount = 0
    var saveHandler: (() throws -> Void)?
    func save() throws {
        saveCallCount += 1
        if let saveHandler {
            try saveHandler()
        }
    }
}

final class TriggerServiceProtocolMock: TriggerServiceProtocol {
    init() {}

    private(set) var configureCallCount = 0
    var configureArgValues = [MenuBarManager]()
    var configureHandler: ((MenuBarManager) -> Void)?
    func configure(menuBarManager: MenuBarManager) {
        configureCallCount += 1
        configureArgValues.append(menuBarManager)
        if let configureHandler {
            configureHandler(menuBarManager)
        }
    }

    private(set) var stopMonitoringCallCount = 0
    var stopMonitoringHandler: (() -> Void)?
    func stopMonitoring() {
        stopMonitoringCallCount += 1
        if let stopMonitoringHandler {
            stopMonitoringHandler()
        }
    }
}

final class HidingServiceProtocolMock: HidingServiceProtocol {
    init() {}
    init(state: HidingState, isAnimating: Bool = false) {
        _state = state
        self.isAnimating = isAnimating
    }

    private var _state: HidingState!
    var state: HidingState {
        get { _state }
        set { _state = newValue }
    }

    var isAnimating: Bool = false
    var isTransitioning: Bool = false

    private(set) var configureCallCount = 0
    var configureArgValues = [StatusItemProtocol]()
    var configureHandler: ((StatusItemProtocol) -> Void)?
    func configure(delimiterItem: StatusItemProtocol) {
        configureCallCount += 1
        configureArgValues.append(delimiterItem)
        if let configureHandler {
            configureHandler(delimiterItem)
        }
    }

    private(set) var toggleCallCount = 0
    var toggleHandler: (() async -> Void)?
    func toggle() async {
        toggleCallCount += 1
        if let toggleHandler {
            await toggleHandler()
        }
    }

    private(set) var showCallCount = 0
    var showHandler: (() async -> Void)?
    func show() async {
        showCallCount += 1
        if let showHandler {
            await showHandler()
        }
    }

    private(set) var hideCallCount = 0
    var hideHandler: (() async -> Void)?
    func hide() async {
        hideCallCount += 1
        if let hideHandler {
            await hideHandler()
        }
    }

    private(set) var configureAlwaysHiddenDelimiterCallCount = 0
    var configureAlwaysHiddenDelimiterArgValues = [StatusItemProtocol?]()
    func configureAlwaysHiddenDelimiter(_ item: StatusItemProtocol?) {
        configureAlwaysHiddenDelimiterCallCount += 1
        configureAlwaysHiddenDelimiterArgValues.append(item)
    }

    private(set) var showAllCallCount = 0
    var showAllHandler: (() async -> Void)?
    func showAll() async {
        showAllCallCount += 1
        if let showAllHandler {
            await showAllHandler()
        }
    }

    private(set) var restoreFromShowAllCallCount = 0
    var restoreFromShowAllHandler: (() async -> Void)?
    func restoreFromShowAll() async {
        restoreFromShowAllCallCount += 1
        if let restoreFromShowAllHandler {
            await restoreFromShowAllHandler()
        }
    }
}

final class KeyboardShortcutsServiceProtocolMock: KeyboardShortcutsServiceProtocol {
    init() {}

    private(set) var registerAllHandlersCallCount = 0
    var registerAllHandlersHandler: (() -> Void)?
    func registerAllHandlers() {
        registerAllHandlersCallCount += 1
        if let registerAllHandlersHandler {
            registerAllHandlersHandler()
        }
    }

    private(set) var unregisterAllHandlersCallCount = 0
    var unregisterAllHandlersHandler: (() -> Void)?
    func unregisterAllHandlers() {
        unregisterAllHandlersCallCount += 1
        if let unregisterAllHandlersHandler {
            unregisterAllHandlersHandler()
        }
    }
}

final class MenuBarAppearanceServiceProtocolMock: MenuBarAppearanceServiceProtocol {
    init() {}

    private(set) var updateAppearanceCallCount = 0
    var updateAppearanceArgValues = [MenuBarAppearanceSettings]()
    var updateAppearanceHandler: ((MenuBarAppearanceSettings) -> Void)?
    func updateAppearance(_ settings: MenuBarAppearanceSettings) {
        updateAppearanceCallCount += 1
        updateAppearanceArgValues.append(settings)
        if let updateAppearanceHandler {
            updateAppearanceHandler(settings)
        }
    }

    private(set) var showCallCount = 0
    var showHandler: (() -> Void)?
    func show() {
        showCallCount += 1
        if let showHandler {
            showHandler()
        }
    }

    private(set) var hideCallCount = 0
    var hideHandler: (() -> Void)?
    func hide() {
        hideCallCount += 1
        if let hideHandler {
            hideHandler()
        }
    }
}

private func warnIfNotSendable<each T>(function: String = #function, _: repeat each T) {
    print("At \(function), the captured arguments are not Sendable, it is not concurrency-safe.")
}

private func warnIfNotSendable<each T: Sendable>(function _: String = #function, _: repeat each T) {}

/// Will be replaced to `Synchronization.Mutex` in future.
private final class MockoloMutex<Value>: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Value
    init(_ initialValue: Value) {
        value = initialValue
    }

    #if compiler(>=6.0)
        borrowing func withLock<Result, E: Error>(_ body: (inout sending Value) throws(E) -> Result) throws(E) -> sending Result {
            lock.lock()
            defer { lock.unlock() }
            return try body(&value)
        }
    #else
        func withLock<Result>(_ body: (inout Value) throws -> Result) rethrows -> Result {
            lock.lock()
            defer { lock.unlock() }
            return try body(&value)
        }
    #endif
}

private struct MockoloUnsafeTransfer<Value>: @unchecked Sendable {
    var value: Value
    init(_ value: Value) {
        self.value = value
    }
}

private struct MockoloHandlerState<Arg, Handler> {
    var argValues: [MockoloUnsafeTransfer<Arg>] = []
    var handler: Handler?
    var callCount: Int = 0
}
