///
/// @Generated by Mockolo
///



import AppKit
import ApplicationServices
import Foundation
@testable import SaneBar


class PermissionServiceProtocolMock: PermissionServiceProtocol {
    init() { }
    init(permissionState: PermissionState, showingPermissionAlert: Bool = false) {
        self._permissionState = permissionState
        self.showingPermissionAlert = showingPermissionAlert
    }



    private var _permissionState: PermissionState!
    var permissionState: PermissionState {
        get { return _permissionState }
        set { _permissionState = newValue }
    }

    private(set) var showingPermissionAlertSetCallCount = 0
    var showingPermissionAlert: Bool = false { didSet { showingPermissionAlertSetCallCount += 1 } }

    private(set) var checkPermissionCallCount = 0
    var checkPermissionHandler: (() -> ())?
    func checkPermission() {
        checkPermissionCallCount += 1
        if let checkPermissionHandler = checkPermissionHandler {
            checkPermissionHandler()
        }
        
    }

    private(set) var requestPermissionCallCount = 0
    var requestPermissionHandler: (() -> ())?
    func requestPermission() {
        requestPermissionCallCount += 1
        if let requestPermissionHandler = requestPermissionHandler {
            requestPermissionHandler()
        }
        
    }

    private(set) var openAccessibilitySettingsCallCount = 0
    var openAccessibilitySettingsHandler: (() -> ())?
    func openAccessibilitySettings() {
        openAccessibilitySettingsCallCount += 1
        if let openAccessibilitySettingsHandler = openAccessibilitySettingsHandler {
            openAccessibilitySettingsHandler()
        }
        
    }

    private(set) var showPermissionRequestCallCount = 0
    var showPermissionRequestHandler: (() -> ())?
    func showPermissionRequest() {
        showPermissionRequestCallCount += 1
        if let showPermissionRequestHandler = showPermissionRequestHandler {
            showPermissionRequestHandler()
        }
        
    }

    private(set) var startPermissionPollingCallCount = 0
    var startPermissionPollingHandler: (() -> ())?
    func startPermissionPolling() {
        startPermissionPollingCallCount += 1
        if let startPermissionPollingHandler = startPermissionPollingHandler {
            startPermissionPollingHandler()
        }
        
    }

    private(set) var stopPermissionPollingCallCount = 0
    var stopPermissionPollingHandler: (() -> ())?
    func stopPermissionPolling() {
        stopPermissionPollingCallCount += 1
        if let stopPermissionPollingHandler = stopPermissionPollingHandler {
            stopPermissionPollingHandler()
        }
        
    }
}

class PersistenceServiceProtocolMock: PersistenceServiceProtocol, @unchecked Sendable {
    var itemConfigurations: [StatusItemModel] = []
    var settings: SaneBarSettings = SaneBarSettings()
    var profiles: [Profile] = []

    func saveItemConfigurations(_ items: [StatusItemModel]) throws {
        itemConfigurations = items
    }

    func loadItemConfigurations() throws -> [StatusItemModel] {
        return itemConfigurations
    }

    func saveSettings(_ settings: SaneBarSettings) throws {
        self.settings = settings
    }

    func loadSettings() throws -> SaneBarSettings {
        return settings
    }

    func saveProfiles(_ profiles: [Profile]) throws {
        self.profiles = profiles
    }

    func loadProfiles() throws -> [Profile] {
        return profiles
    }

    func clearAll() throws {
        itemConfigurations = []
        settings = SaneBarSettings()
        profiles = []
    }

    func mergeWithSaved(scannedItems: [StatusItemModel], savedItems: [StatusItemModel]) -> [StatusItemModel] {
        return scannedItems
    }
}

class AccessibilityServiceProtocolMock: AccessibilityServiceProtocol {
    init() { }
    init(isTrusted: Bool = false, isScanning: Bool = false, lastScanDate: Date? = nil, lastError: AccessibilityError? = nil) {
        self.isTrusted = isTrusted
        self.isScanning = isScanning
        self.lastScanDate = lastScanDate
        self.lastError = lastError
    }



    var isTrusted: Bool = false


    var isScanning: Bool = false


    var lastScanDate: Date? = nil


    var lastError: AccessibilityError? = nil

    private(set) var requestPermissionCallCount = 0
    var requestPermissionHandler: (() -> ())?
    func requestPermission() {
        requestPermissionCallCount += 1
        if let requestPermissionHandler = requestPermissionHandler {
            requestPermissionHandler()
        }
        
    }

    private(set) var scanMenuBarItemsCallCount = 0
    var scanMenuBarItemsHandler: (() async throws -> [StatusItemModel])?
    func scanMenuBarItems() async throws -> [StatusItemModel] {
        scanMenuBarItemsCallCount += 1
        if let scanMenuBarItemsHandler = scanMenuBarItemsHandler {
            return try await scanMenuBarItemsHandler()
        }
        return [StatusItemModel]()
    }
}



